### ISSUE TITLE
As a developer, I would like to create a sample database so that we can work on that as the project goes on.

### ISSUE THREAD

**Issue by OmrParlakturk** [rabiayunusoglu/afet_kurtar#2]

**Comment by rabiayunusoglu** [comment]
CREATE TABLE `authorized_user` (
  `authorized_id` int NOT NULL,
  `authorized_name` varchar(45) NOT NULL,
  `institution` varchar(45) NOT NULL,
  PRIMARY KEY (`authorized_id`)
) 

CREATE TABLE `disaster_events` (
  `disasterID` int NOT NULL,
  `disasterType` varchar(45) NOT NULL,
  `emergencyLevel` varchar(45) DEFAULT NULL,
  `latitudeStart` varchar(45) DEFAULT NULL,
  `latitudeEnd` varchar(45) DEFAULT NULL,
  `longitudeStart` varchar(45) DEFAULT NULL,
  `longitudeEnd` varchar(45) DEFAULT NULL,
  `subports` varchar(45) DEFAULT NULL,
  `date` varchar(45) DEFAULT NULL,
  `disaster_eventscol` varchar(45) NOT NULL,
  PRIMARY KEY (`disasterID`)
)


CREATE TABLE `notices` (
  `type` int NOT NULL,
  `latitude` varchar(45) DEFAULT NULL,
  `longitude` varchar(45) DEFAULT NULL,
  `message` varchar(500) DEFAULT NULL,
  `imageURL` varchar(300) DEFAULT NULL,
  PRIMARY KEY (`type`)
) 


CREATE TABLE `personel_user` (
  `personel_id` int NOT NULL,
  `name` varchar(45) NOT NULL,
  `personel_role` varchar(45) NOT NULL,
  `team_id` int NOT NULL,
  `latitude` varchar(45) NOT NULL,
  `longitude` varchar(45) NOT NULL,
  `institution` varchar(45) NOT NULL,
  PRIMARY KEY (`personel_id`)
) 

CREATE TABLE `subports` (
  `subportID` int NOT NULL,
  `disasterID` int NOT NULL,
  `address` varchar(100) NOT NULL,
  `latitude` varchar(45) NOT NULL,
  `longitude` varchar(45) NOT NULL,
  `missingPerson` varchar(45) DEFAULT NULL,
  `assignedTeamID` int NOT NULL,
  `rescuedPerson` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`subportID`)
)
CREATE TABLE `teams` (
  `team_id` int NOT NULL,
  `member_id` int NOT NULL,
  `leader_id` int NOT NULL,
  `assignedSubport_id` int NOT NULL,
  `status` varchar(45) NOT NULL,
  `needManPowerl` varchar(45) NOT NULL,
  `needEquipment` varchar(45) NOT NULL,
  PRIMARY KEY (`team_id`)
) 

CREATE TABLE `user` (
  `user_id` int NOT NULL,
  `user_type` int NOT NULL,
  `username` varchar(16) NOT NULL,
  `email` varchar(255) DEFAULT NULL,
  `password` varchar(32) NOT NULL,
  `create_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id`,`user_type`)
) 
CREATE TABLE `volunteer_user` (
  `volunteerID` int NOT NULL,
  `volunteerName` varchar(45) NOT NULL,
  `adress` varchar(300) NOT NULL,
  `isExperienced` varchar(500) NOT NULL,
  `haveFirstAidCert` varchar(500) NOT NULL,
  `requestForJoiningDisasterEvent` varchar(500) NOT NULL,
  `responseForJoiningDisasterEvent` varchar(500) NOT NULL,
  `assignedTeamID` int NOT NULL,
  `role` varchar(45) NOT NULL,
  `latitude` varchar(45) NOT NULL,
  `longtitude` varchar(45) NOT NULL,
  PRIMARY KEY (`volunteerID`)
) 
INSERT INTO `afet_kurtar`.`authorized_user` (`authorized_id`, `authorized_name`, `institution`) VALUES ('1', 'ömer', 'afad');
INSERT INTO `afet_kurtar`.`authorized_user` (`authorized_id`, `authorized_name`, `institution`) VALUES ('2', 'rabia', 'afad');
INSERT INTO `afet_kurtar`.`authorized_user` (`authorized_id`, `authorized_name`, `institution`) VALUES ('3', 'okan', 'akut');
INSERT INTO `afet_kurtar`.`authorized_user` (`authorized_id`, `authorized_name`, `institution`) VALUES ('4', 'tarık', 'akut');
INSERT INTO `afet_kurtar`.`authorized_user` (`authorized_id`, `authorized_name`, `institution`) VALUES ('5', 'derda', 'akut');
INSERT INTO `afet_kurtar`.`disaster_events` (`disasterID`, `disasterType`, `emergencyLevel`, `latitudeStart`, `latitudeEnd`, `longitudeStart`, `longitudeEnd`, `subports`, `date`, `disaster_eventscol`) VALUES ('1', 'deprem', '1', '15°45\'15\"K', '15°45\'15\"K', '30°10\'7\"D', '30°10\'7\"D', 'none', '12.01.2021', 'diasaster');
INSERT INTO `afet_kurtar`.`disaster_events` (`disasterID`, `disasterType`, `emergencyLevel`, `latitudeStart`, `latitudeEnd`, `longitudeStart`, `longitudeEnd`, `subports`, `date`, `disaster_eventscol`) VALUES ('2', 'sel', '2', '15°45\'15\"K', '15°45\'15\"K', '30°10\'7\"D', '30°10\'7\"D', 'yes', '11.10.2006', 'diasaster');
INSERT INTO `afet_kurtar`.`disaster_events` (`disasterID`, `disasterType`, `emergencyLevel`, `latitudeStart`, `latitudeEnd`, `longitudeStart`, `longitudeEnd`, `subports`, `date`, `disaster_eventscol`) VALUES ('3', 'yangın', '3', '15°45\'15\"K', '15°45\'15\"K', '30°10\'7\"D', '30°10\'7\"D', 'no', '15.03.2020', 'diasaster');
INSERT INTO `afet_kurtar`.`disaster_events` (`disasterID`, `disasterType`, `emergencyLevel`, `latitudeStart`, `latitudeEnd`, `longitudeStart`, `longitudeEnd`, `subports`, `date`, `disaster_eventscol`) VALUES ('4', 'orman yangını', '1', '15°45\'15\"K', '15°45\'15\"K', '30°10\'7\"D', '30°10\'7\"D', 'yes', '13.12.1998', 'diasaster');
INSERT INTO `afet_kurtar`.`disaster_events` (`disasterID`, `disasterType`, `emergencyLevel`, `latitudeStart`, `latitudeEnd`, `longitudeStart`, `longitudeEnd`, `subports`, `date`) VALUES ('5', 'heyelan', '1', '15°45\'15\"K', '15°45\'15\"K', '30°10\'7\"D', '30°10\'7\"D', 'yes', '23.02.2010','diasaster');
INSERT INTO `afet_kurtar`.`notices` (`type`, `latitude`, `longitude`, `message`, `imageURL`) VALUES ('1', '15°24\'15\"K', '15°24\'15\"K', 'görev  tamamlandı.', 'https://www.google.com/search?gs_ssp=eJzj4tLP1TcwKspKyS4wYPTiLMlPSlJILTm8BwBU-ggA&q=tobb+et%C3%BC&oq=tob&aqs=chrome.1.69i57j46i39j0i433l2j46i433j69i65j69i61l2.1925j0j7&sourceid=chrome&ie=UTF-8');
INSERT INTO `afet_kurtar`.`notices` (`type`, `latitude`, `longitude`, `message`, `imageURL`) VALUES ('2', '15°24\'15\"K', '15°24\'15\"K', 'olay yerine varıldı.', 'https://www.google.com/search?gs_ssp=eJzj4tLP1TcwKspKyS4wYPTiLMlPSlJILTm8BwBU-ggA&q=tobb+et%C3%BC&oq=tob&aqs=chrome.1.69i57j46i39j0i433l2j46i433j69i65j69i61l2.1925j0j7&sourceid=chrome&ie=UTF-8');
INSERT INTO `afet_kurtar`.`notices` (`type`, `latitude`, `longitude`, `message`, `imageURL`) VALUES ('3', '15°24\'15\"K', '15°24\'15\"K', 'içeriye giriyoruz', 'https://www.google.com/search?gs_ssp=eJzj4tLP1TcwKspKyS4wYPTiLMlPSlJILTm8BwBU-ggA&q=tobb+et%C3%BC&oq=tob&aqs=chrome.1.69i57j46i39j0i433l2j46i433j69i65j69i61l2.1925j0j7&sourceid=chrome&ie=UTF-8');
INSERT INTO `afet_kurtar`.`notices` (`type`, `latitude`, `longitude`, `message`, `imageURL`) VALUES ('4', '15°24\'15\"K', '15°24\'15\"K', 'tamam', 'https://www.google.com/search?gs_ssp=eJzj4tLP1TcwKspKyS4wYPTiLMlPSlJILTm8BwBU-ggA&q=tobb+et%C3%BC&oq=tob&aqs=chrome.1.69i57j46i39j0i433l2j46i433j69i65j69i61l2.1925j0j7&sourceid=chrome&ie=UTF-8');
INSERT INTO `afet_kurtar`.`personel_user` (`personel_id`, `name`, `personel_role`, `team_id`, `latitude`, `longitude`, `institution`) VALUES ('12345', 'ahmet', 'lider yardımcısı', '1', '15°24\'15\"K', '15°24\'15\"K', 'afat');
INSERT INTO `afet_kurtar`.`personel_user` (`personel_id`, `name`, `personel_role`, `team_id`, `latitude`, `longitude`, `institution`) VALUES ('12346', 'mehmet', 'yardımcı', '2', '15°24\'15\"K', '15°24\'15\"K', 'akut');
INSERT INTO `afet_kurtar`.`subports` (`subportID`, `disasterID`, `address`, `latitude`, `longitude`, `missingPerson`, `assignedTeamID`, `rescuedPerson`) VALUES ('1', '1', 'Söğütözü, Söğütözü Cd. No:43, 06510 Çankaya/Ankara', '15°24\'15\"K', '15°24\'15\"K', '12', '2', '11');
INSERT INTO `afet_kurtar`.`subports` (`subportID`, `disasterID`, `address`, `latitude`, `longitude`, `missingPerson`, `assignedTeamID`, `rescuedPerson`) VALUES ('2', '2', 'Söğütözü, Söğütözü Cd. No:43, 06510 Çankaya/Ankara', '15°24\'15\"K', '15°24\'15\"K', '1', '2', '1');
INSERT INTO `afet_kurtar`.`subports` (`subportID`, `disasterID`, `address`, `latitude`, `longitude`, `missingPerson`, `assignedTeamID`, `rescuedPerson`) VALUES ('3', '2', 'Söğütözü, Söğütözü Cd. No:43, 06510 Çankaya/Ankara', '15°24\'15\"K', '15°24\'15\"K', '13', '2', '2');
INSERT INTO `afet_kurtar`.`teams` (`team_id`, `member_id`, `leader_id`, `assignedSubport_id`, `status`, `needManPowerl`, `needEquipment`) VALUES ('1', '2', '1', '2', 'iyi', '0', '10 battaniye');
INSERT INTO `afet_kurtar`.`teams` (`team_id`, `member_id`, `leader_id`, `assignedSubport_id`, `status`, `needManPowerl`, `needEquipment`) VALUES ('2', '4', '5', '5', 'orta', '1', '10 ısıtıcı');
INSERT INTO `afet_kurtar`.`teams` (`team_id`, `member_id`, `leader_id`, `assignedSubport_id`, `status`, `needManPowerl`, `needEquipment`) VALUES ('3', '2', '1', '1', 'kötü', '2', '2 serum');
INSERT INTO `afet_kurtar`.`user` (`user_id`, `user_type`, `username`, `email`, `password`, `create_time`) VALUES ('1', '2', 'rabia', 'ryunusoglu@etu.edu.tr', '12345', '2012-02-20 21:00:00');
INSERT INTO `afet_kurtar`.`volunteer_user` (`volunteerID`, `volunteerName`, `adress`, `isExperienced`, `haveFirstAidCert`, `requestForJoiningDisasterEvent`, `responseForJoiningDisasterEvent`, `assignedTeamID`, `role`, `latitude`, `longtitude`) VALUES ('1', 'ali', 'Söğütözü, Söğütözü Cd. No:43, 06510 Çankaya/Ankara', '2 yıl', 'yes', 'gönüllü olarak katılmak istiyorum', 'kabul edilmiştir.', '1', 'lider', '15°24\'15\"K', '15°24\'15\"K');
INSERT INTO `afet_kurtar`.`volunteer_user` (`volunteerID`, `volunteerName`, `adress`, `isExperienced`, `haveFirstAidCert`, `requestForJoiningDisasterEvent`, `responseForJoiningDisasterEvent`, `assignedTeamID`, `role`, `latitude`, `longtitude`) VALUES ('2', 'ayşe', 'Söğütözü, Söğütözü Cd. No:43, 06510 Çankaya/Ankara', '1 yıl', 'no', 'gönüllü olarak katılmak istiyorum', 'kabul edilmiştir.', '2', 'yardımcı lider', '15°24\'15\"K', '15°24\'15\"K');
