### ISSUE TITLE
As a developer, I would like to create an ER diagram for the system data model.

### ISSUE THREAD

**Issue by OmrParlakturk** [rabiayunusoglu/afet_kurtar#3]

**Comment by rabiayunusoglu** [comment]
ER diagram is created.

Source: 
https://docs.google.com/document/d/1TEoNV54Rb_7xQZuNDvwH6B4Z8ONFHaMO_wVooM9baRs/edit?usp=sharing



![Ekran Görüntüsü (230)](https://user-images.githubusercontent.com/55558174/107881673-70e50700-6ef6-11eb-911d-46c6a6cf7961.png)
