### ISSUE TITLE
As a developer, I would like to create an architectural overall diagram for the system showing the components and their event/API/database intersections.

### ISSUE THREAD

**Issue by OmrParlakturk** [rabiayunusoglu/afet_kurtar#4]

**Comment by drdkymk** [comment]
### Highlevel
![Mimari Diyagram](https://user-images.githubusercontent.com/50781454/107887351-9550db80-6f16-11eb-937d-f1c00d992325.png)

**Component | Related To**
1 | 5,7
5 | 1,7
6 | 7
7 | DB
8 | 7
9 | 7,8,10
10 | 7,Google Maps API
11 | 14,15
12 | 7,Signal API
13 | Google Maps API
14 | 7
16 | Google Maps API

**Comment by drdkymk** [comment]
Each component is assigned to team members.

![Mimari Diyagram 2](https://user-images.githubusercontent.com/50781454/107887601-4015c980-6f18-11eb-8821-58dcb0fc754d.png)
